# Generated by Django 6.0 on 2025-12-11 09:56

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='alternative_text',
            field=models.CharField(blank=True, help_text='Alternative text', max_length=250),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='cm_watermark',
            field=models.BooleanField(default=False, help_text='CM Watermark?'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='color',
            field=models.CharField(blank=True, help_text='Color option', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='double_width',
            field=models.BooleanField(default=False, help_text='Double width on home page (requires wide thumbnail)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature post (requires tall thumbnail)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='hide_title',
            field=models.BooleanField(default=False, help_text='Hide title when using text in thumbnail'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='Choose an icon image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='page_header',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional page header content'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='page_header_image',
            field=models.ForeignKey(blank=True, help_text='Choose an image for the page header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='source_link',
            field=models.URLField(blank=True, help_text="Link to the article's source"),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tall_thumbnail',
            field=models.ForeignKey(blank=True, help_text='Tall thumbnail (540px x 750px) - used on Section Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='title_position',
            field=models.CharField(blank=True, help_text='Position of the title', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='twitter_body',
            field=models.TextField(blank=True, help_text='Twitter body text'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='vimeo_id',
            field=models.CharField(blank=True, help_text='Vimeo Video ID', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='white_text',
            field=models.BooleanField(default=False, help_text='White text for darker images'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='wide_thumbnail',
            field=models.ForeignKey(blank=True, help_text='Wide thumbnail (1140px x 750px) - used on Home Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='article_types',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select article types', to='blog.articletype'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='locations',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select locations', to='blog.location'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='sectors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select sectors', to='blog.sector'),
        ),
    ]
