# Generated by Django 6.0 on 2025-12-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articletype_location_sector_and_more'),
    ]

    operations = [
    ]
