# Generated by Django 6.0 on 2025-12-11 11:54

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20251211_1015'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('title_position', models.CharField(blank=True, help_text='Position of the title', max_length=50)),
                ('page_header', wagtail.fields.RichTextField(blank=True, help_text='Optional page header content')),
                ('featured', models.BooleanField(default=False, help_text='Feature post (requires tall thumbnail)')),
                ('double_width', models.BooleanField(default=False, help_text='Double width on home page (requires wide thumbnail)')),
                ('white_text', models.BooleanField(default=False, help_text='White text for darker images')),
                ('hide_title', models.BooleanField(default=False, help_text='Hide title when using text in thumbnail')),
                ('color', models.CharField(blank=True, help_text='Color option', max_length=50)),
                ('cm_watermark', models.BooleanField(default=False, help_text='CM Watermark?')),
                ('alternative_text', models.CharField(blank=True, help_text='Alternative text', max_length=250)),
                ('twitter_body', models.TextField(blank=True, help_text='Twitter body text')),
                ('vimeo_id', models.CharField(blank=True, help_text='Vimeo Video ID', max_length=50)),
                ('source_link', models.URLField(blank=True, help_text="Link to the article's source")),
                ('article_types', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select article types', to='blog.articletype')),
                ('icon', models.ForeignKey(blank=True, help_text='Choose an icon image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('locations', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select locations', to='blog.location')),
                ('page_header_image', models.ForeignKey(blank=True, help_text='Choose an image for the page header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('sectors', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select sectors', to='blog.sector')),
                ('tall_thumbnail', models.ForeignKey(blank=True, help_text='Tall thumbnail (540px x 750px) - used on Section Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('wide_thumbnail', models.ForeignKey(blank=True, help_text='Wide thumbnail (1140px x 750px) - used on Home Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='KeyFactsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('key_facts', wagtail.fields.RichTextField(blank=True, help_text='List of key facts')),
                ('header_image', models.ForeignKey(blank=True, help_text='Choose a header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
