# Generated by Django 5.2.9 on 2025-12-16 09:33

import json
import wagtail.fields
from django.db import migrations


def convert_richtext_to_streamfield(apps, schema_editor):
    """Convert existing RichText data to empty StreamField JSON"""
    BlogPage = apps.get_model('blog', 'BlogPage')
    ArticlePage = apps.get_model('blog', 'ArticlePage')
    
    # Convert all BlogPages with non-empty body to empty JSON array
    for page in BlogPage.objects.all():
        if page.body and page.body.strip():
            # If there's existing content, wrap it in a paragraph block
            page.body = json.dumps([{
                'type': 'paragraph',
                'value': page.body
            }])
        else:
            page.body = json.dumps([])
        page.save(update_fields=['body'])
    
    # Convert all ArticlePages
    for page in ArticlePage.objects.all():
        if page.body and page.body.strip():
            page.body = json.dumps([{
                'type': 'paragraph',
                'value': page.body
            }])
        else:
            page.body = json.dumps([])
        page.save(update_fields=['body'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_articletype_id_alter_location_id_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_richtext_to_streamfield, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 7), ('embed', 8), ('document', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Enter the quote text', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Person's name", 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Job title', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Company name', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('quote', 3), ('name', 4), ('job_title', 5), ('company', 6)]], {}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 7), ('embed', 8), ('document', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Enter the quote text', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Person's name", 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Job title', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Company name', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('quote', 3), ('name', 4), ('job_title', 5), ('company', 6)]], {}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})}),
        ),
    ]
