# Generated by Django 4.2.7 on 2026-02-11 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_whycashmattersfeaturepage_feature_cards'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Custom Open Graph description (defaults to intro if empty)', verbose_name='OG Description'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Custom Open Graph image (defaults to page header image if empty)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='OG Image'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Custom Open Graph title (defaults to page title if empty)', max_length=255, verbose_name='OG Title'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Custom Open Graph description (defaults to intro if empty)', verbose_name='OG Description'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Custom Open Graph image (defaults to page header image if empty)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='OG Image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Custom Open Graph title (defaults to page title if empty)', max_length=255, verbose_name='OG Title'),
        ),
    ]
