# Generated by Django 6.0.1 on 2026-02-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_add_og_fields'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_number', models.CharField(help_text='The percentage or number to display, e.g. 22%', max_length=10)),
                ('description', models.CharField(help_text='Fact description, e.g. Cash is used for 22% of POS payments in Chile', max_length=255)),
                ('country', models.CharField(help_text='Country name', max_length=100)),
                ('stat_color', models.CharField(choices=[('text-stat-yellow', 'Yellow'), ('text-stat-blue', 'Blue'), ('text-stat-teal', 'Teal'), ('text-stat-rust', 'Rust')], default='text-stat-yellow', help_text='Color for the stat number', max_length=20)),
                ('background_image_alt', models.CharField(blank=True, help_text='Alt text for the background image', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Show on homepage')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order of display (lower = first)')),
                ('background_image', models.ForeignKey(blank=True, help_text='Background photo displayed below/above the stat card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('download_image', models.ForeignKey(blank=True, help_text='Downloadable fact card image (shown when user clicks Download)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Key Fact',
                'verbose_name_plural': 'Key Facts',
                'ordering': ['sort_order'],
            },
        ),
    ]
